### PR TITLE
Disable editing for files inside Pods directory

### PR DESCRIPTION
**Pull request by zenangst**
We use a lot of CocoaPods at work and it so happens that from time to time we have brain farts and start editing them directly in the project. To avoid this we were thinking about writing a plugin... and then we found Helmet. However Helmet does not support this, hence me making this pull request with the tiny change that we had to make.

Hope you like it.

### CODE REVIEW

**Comment by 3lvis** [comment]
:+1: :+1:

**Comment by brianmichel** [comment]
**YOU WENT OVER MY HELMET!**

Just kidding, I like this a bunch. This will not prevent the editing of any local pods though, so it doesn't cover the entire CocoaPods spectrum. I've been toying with the idea of allowing people to enter their own blocked paths in addition to the built in ones. 

Do you think that would useful in combination with something like this?

**Comment by zenangst** [comment]
Yeah I think that would be a great addition :+1:

**Comment by brianmichel** [comment]
@zenangst awesome, I will test your additions when I get home from work today!

**Comment by brianmichel** [comment]
Looks good to me!

**Comment by zenangst** [comment]
:star2:

**Comment by 3lvis** [comment]
+:100: ! great work guys :dancers:

**Pull request merged**
